# Generated by Django 5.1.15 on 2026-06-28 20:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('commune', models.CharField(blank=True, max_length=80, verbose_name='Commune')),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('pro', 'Entreprise / Pro')], default='particulier', max_length=20, verbose_name='Type')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('zones', models.CharField(blank=True, max_length=255, verbose_name='Zones couvertes')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
            ],
            options={
                'verbose_name': 'Commis',
                'verbose_name_plural': 'Commis',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FormuleSecretariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, unique=True, verbose_name='Formule')),
                ('prix_mensuel', models.PositiveIntegerField(verbose_name='Tarif mensuel (FCFA)')),
                ('rdv_max_mois', models.PositiveIntegerField(blank=True, help_text='Laisser vide = illimité.', null=True, verbose_name='RDV pris en charge / mois')),
                ('recap_dimanche', models.BooleanField(default=True, verbose_name='Récapitulatif (dimanche)')),
                ('rappels_30min', models.BooleanField(default=True, verbose_name='Rappels 30 min avant RDV')),
                ('confirmation_tel', models.BooleanField(default=False, verbose_name='Confirmation téléphonique')),
                ('gestion_contacts', models.BooleanField(default=False, verbose_name='Gestion carnet de contacts')),
                ('recherche_infos', models.BooleanField(default=False, verbose_name="Recherche d'infos / tarifs")),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Formule Secrétariat',
                'verbose_name_plural': 'Formules Secrétariat',
                'ordering': ['ordre', 'prix_mensuel'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('standard', 'Zone Standard'), ('etendue', 'Zone Étendue'), ('speciale', 'Zone Spéciale')], max_length=20, unique=True, verbose_name='Type de zone')),
                ('communes', models.CharField(blank=True, max_length=255, verbose_name='Communes concernées')),
                ('frais', models.CharField(blank=True, help_text='Ex. : « Inclus », « + 1 000 à 2 000 FCFA », « Sur devis ».', max_length=120, verbose_name='Frais de déplacement')),
            ],
            options={
                'verbose_name': 'Zone de couverture',
                'verbose_name_plural': 'Zones de couverture',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Référence')),
                ('contact_nom', models.CharField(blank=True, max_length=120, verbose_name='Nom (demande)')),
                ('contact_tel', models.CharField(blank=True, max_length=30, verbose_name='Téléphone (demande)')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email (demande)')),
                ('type_service', models.CharField(choices=[('courses_marche', 'Courses au marché'), ('pharmacie', 'Pharmacie & ordonnances'), ('demarches', 'Démarches administratives'), ('shopping', 'Shopping & cadeaux'), ('colis', 'Dépôt & retrait de colis'), ('documents', 'Retrait de documents'), ('secretariat', 'Secrétariat à distance'), ('autre', 'Autre / sur-mesure')], default='courses_marche', max_length=20, verbose_name='Service')),
                ('description', models.TextField(blank=True, verbose_name='Description du besoin')),
                ('adresse_retrait', models.CharField(blank=True, max_length=255, verbose_name='Adresse de retrait')),
                ('adresse_livraison', models.CharField(blank=True, max_length=255, verbose_name='Adresse de livraison')),
                ('creneau', models.CharField(blank=True, max_length=120, verbose_name='Créneau souhaité')),
                ('urgence', models.BooleanField(default=False, verbose_name='Urgence (+50 %)')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('formulaire', 'Formulaire site'), ('telephone', 'Téléphone')], default='formulaire', max_length=20, verbose_name='Canal')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('qualifiee', 'Qualifiée'), ('affectee', 'Affectée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], default='nouvelle', max_length=20, verbose_name='Statut')),
                ('tarif_base', models.PositiveIntegerField(default=0, verbose_name='Tarif de base (FCFA)')),
                ('frais_deplacement', models.PositiveIntegerField(default=0, verbose_name='Frais de déplacement (FCFA)')),
                ('supplement_urgence', models.PositiveIntegerField(default=0, verbose_name='Supplément urgence (FCFA)')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total (FCFA)')),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile money (Orange/MTN/Moov/Wave)'), ('virement', 'Virement')], max_length=20, verbose_name='Mode de paiement')),
                ('paye_avant_mission', models.BooleanField(default=False, help_text='Règle CGV : les frais sont réglés avant le début de la mission.', verbose_name='Réglé avant la mission')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Reçue le')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='gestion.client', verbose_name='Client')),
                ('commis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='gestion.commis', verbose_name='Commis affecté')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Mission / Demande',
                'verbose_name_plural': 'Missions / Demandes',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField(default=django.utils.timezone.now, verbose_name='Début')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('terminee', 'Terminée')], default='active', max_length=20, verbose_name='Statut')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='gestion.client', verbose_name='Client')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.formulesecretariat', verbose_name='Formule')),
            ],
            options={
                'verbose_name': 'Souscription Secrétariat',
                'verbose_name_plural': 'Souscriptions Secrétariat',
                'ordering': ['-debut'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile money'), ('virement', 'Virement')], default='especes', max_length=20, verbose_name='Mode')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('regle', 'Réglé')], default='attente', max_length=20, verbose_name='Statut')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.mission', verbose_name='Mission')),
                ('souscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.souscription', verbose_name='Souscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date'],
            },
        ),
    ]
